plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id 'io.freefair.lombok'
}

lombok {
    version = "1.18.40" // 手动指定支持 Java 25 的版本
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    //implementation "com.terraformersmc:modmenu:17.0.0-alpha.1"
    implementation("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    compileOnly("maven.modrinth:watermedia:${watermedia_version}")

    include(implementation("org.mvel:mvel2:2.5.0.Final"))
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
