org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=chatbox
mod.name=ChatBox
mod.group=com.zhenshiz
mod.version=1.1

deps.fabric-loom=1.14-SNAPSHOT
deps.moddev=2.0.131
deps.fabric-loader=0.18.3

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.cloth-config=[VERSIONED]
deps.watermedia=2.1.25

deps.rhino=[VERSIONED]
deps.kubejs=[VERSIONED]
deps.terra-entity=[VERSIONED]
deps.geckolib=[VERSIONED]

publish.modrinth=
publish.curseforge=
#publish.additionalVersions=