modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0 license"

[[mods]]
modId = "chatbox"
version = "1.0.8"
displayName = "ChatBox"
authors = "zhenshiz"
description = '''
GalGame DialogBox
'''
logoFile = "icon.png"

[[dependencies.chatbox]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.199,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatbox]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "chatbox.mixins.json"
