plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers.from(at.absolutePath)
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.5"
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly "io.github.llamalad7:mixinextras-common:0.3.5"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.5"

    implementation "maven.modrinth:watermedia:${watermedia_version}"
    compileOnly("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    implementation "org.mvel:mvel2:2.5.0.Final"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

