plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'io.freefair.lombok'
}

lombok {
    version = "1.18.40"
}

repositories {
    mavenLocal()
    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net')
    }
    maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")

    compileOnly("com.terraformersmc:modmenu:18.0.0-alpha.6")

    compileOnly("maven.modrinth:watermedia:${watermedia_version}")

    implementation("org.mvel:mvel2:2.5.0.Final")

    implementation files("libs/${graal_name}")
    implementation files("libs/${nekojs_name}")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
