plugins {
    id 'net.neoforged.moddev'
}

apply from: rootProject.file('loader.gradle')

dependencies {
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")

    compileOnly("com.terraformersmc:modmenu:18.0.0-alpha.6")

    compileOnly("maven.modrinth:watermedia:${watermedia_version}")

    implementation("org.mvel:mvel2:2.5.0.Final")

    implementation files("libs/${graal_name}")
    compileOnly files("libs/${nekojs_name}")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers.from(at.absolutePath)

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            setGameDirectory file("../runs/client")
        }
        server {
            server()
            setGameDirectory file("../runs/server")
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
